import Link from 'next/link';
import {ArrowRight,ShieldCheck,Search,MapPinned,Heart,GitCompare} from 'lucide-react';
import {Hero,DestinationCard,ServiceGrid,TravelCard} from '@/components/Platform';
import {destinations,offers} from '@/lib/data';
export default function Home(){return <>
<Hero/>
<section className="container py-20"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow-blue">DISCOVER</p><h2 className="mt-2 text-4xl font-black">Où vous emmènera votre prochaine escapade ?</h2><p className="mt-3 max-w-2xl text-slate-600">Une recherche simple, des destinations inspirantes et une demande qualifiée quand vous êtes prêt.</p></div><Link href="/destinations" className="hidden font-extrabold text-[#1F3F93] md:flex">Toutes les destinations <ArrowRight/></Link></div><div className="mt-8 grid gap-5 md:grid-cols-3">{destinations.slice(0,3).map(d=><DestinationCard key={d.slug} d={d}/>)}</div></section>
<section className="bg-white py-20"><div className="container"><p className="eyebrow-blue">SERVICES</p><h2 className="mt-2 text-4xl font-black">Tout pour préparer votre voyage</h2><p className="mt-3 mb-8 max-w-2xl text-slate-600">Les services communiqués par In Vacation Travel, présentés dans une expérience digitale claire.</p><ServiceGrid/></div></section>
<section className="container py-20"><div className="flex items-end justify-between"><div><p className="eyebrow-blue">VOYAGES</p><h2 className="mt-2 text-4xl font-black">Explorez les possibilités</h2></div><Link href="/voyages" className="font-extrabold text-[#1F3F93]">Voir tout <ArrowRight className="inline"/></Link></div><div className="mt-8 grid gap-5 md:grid-cols-2">{offers.slice(0,4).map(o=><TravelCard key={o.slug} offer={o}/>)}</div></section>
<section className="bg-[#071A3D] py-20 text-white"><div className="container grid gap-12 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><p className="eyebrow">POURQUOI NOUS</p><h2 className="mt-3 text-4xl font-black">Une plateforme pensée pour passer de l’inspiration à la demande.</h2><div className="mt-8 grid gap-5"><div className="flex gap-4"><ShieldCheck className="text-[#FFD21F]"/><div><b>Informations claires</b><p className="mt-1 text-sm text-slate-300">Les prix et disponibilités non confirmés restent indiqués comme tels.</p></div></div><div className="flex gap-4"><MapPinned className="text-[#FFD21F]"/><div><b>Découverte visuelle</b><p className="mt-1 text-sm text-slate-300">Destinations, cartes et pages détaillées pour préparer votre projet.</p></div></div><div className="flex gap-4"><Heart className="text-[#FFD21F]"/><div><b>Favoris & comparaison</b><p className="mt-1 text-sm text-slate-300">Enregistrez et comparez jusqu’à 3 propositions sur votre appareil.</p></div></div></div></div><div className="rounded-3xl bg-white p-8 text-[#071A3D] shadow-2xl"><Search className="text-[#1F3F93]" size={32}/><h3 className="mt-4 text-2xl font-black">Votre projet, en quelques clics.</h3><p className="mt-2 leading-7 text-slate-600">Dites-nous destination, dates, voyageurs et préférences. Nous transformons votre recherche en demande exploitable.</p><Link href="/demande" className="btn-yellow mt-6">Préparer mon voyage <ArrowRight size={17}/></Link></div></div></section>
<section className="container py-20"><div className="rounded-[32px] bg-[#FFD21F] p-8 md:p-12"><div className="max-w-3xl"><p className="text-xs font-black tracking-[.15em] text-[#071A3D]">KHEMIS MILIANA · AÏN DEFLA</p><h2 className="mt-3 text-4xl font-black text-[#071A3D]">Prêt à préparer votre prochain voyage ?</h2><p className="mt-3 text-[#071A3D]/75">Demandez un devis ou contactez directement l’agence.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/demande" className="btn-blue">Demander un devis <ArrowRight size={17}/></Link><Link href="/contact" className="btn-white">Nous contacter</Link></div></div></div></section>
</>}
